# Generated by Django 6.0.3 on 2026-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Eindeutiger Schlüssel, z.B. wordpress-mariadb', max_length=80, unique=True)),
                ('label', models.CharField(help_text='Anzeigename, z.B. WordPress + MariaDB', max_length=100)),
                ('icon', models.CharField(default='bi-collection', help_text='Bootstrap Icons Klasse, z.B. bi-globe', max_length=60)),
                ('category', models.CharField(default='Sonstige', help_text='Kategorie für Gruppieurng, z.B. CMS', max_length=50)),
                ('stack_data', models.JSONField(help_text='Stack-Konfiguration: pod_name, restart_policy, mode, host_network, containers, init_containers')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'category', 'label'],
            },
        ),
    ]
