# Generated by Django 6.0.3 on 2026-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_stacktemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressumSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name / Firma')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('zusatz', models.TextField(blank=True, verbose_name='Zusätzliche Angaben (Haftung, Urheberrecht etc.)')),
                ('letzte_aenderung', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impressum',
                'verbose_name_plural': 'Impressum',
            },
        ),
    ]
