# Generated by Django 6.0.3 on 2026-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_impressumsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Podman Kube Generator', max_length=100, verbose_name='Site-Name (og:site_name)')),
                ('home_title', models.CharField(default='Podman Kube Generator – Kubernetes YAML für podman play kube', max_length=120, verbose_name='Homepage Title-Tag')),
                ('home_description', models.TextField(default='Kubernetes YAML für podman play kube kostenlos generieren. Pod-Konfigurationen, Multi-Container-Stacks und systemd Quadlet-Anleitungen in Sekunden erstellen.', max_length=300, verbose_name='Homepage Meta-Description')),
                ('keywords', models.CharField(default='podman, kubernetes yaml, podman play kube, container, pod generator, quadlet, systemd, rootless container', max_length=500, verbose_name='Meta-Keywords')),
                ('og_image_url', models.URLField(blank=True, help_text='Absoluter URL zum Vorschaubild, z.B. https://example.com/og.png', verbose_name='OG-Image URL (Social Media Vorschau)')),
                ('google_site_verification', models.CharField(blank=True, help_text='Inhalt des content-Attributs im meta-Tag', max_length=200, verbose_name='Google Site Verification')),
                ('robots_txt', models.TextField(default='User-agent: *\nAllow: /\nDisallow: /admin/\n\nSitemap: /sitemap.xml', help_text='Wird direkt als /robots.txt ausgeliefert. {site_url} wird durch die Site-URL ersetzt.', verbose_name='robots.txt Inhalt')),
            ],
            options={
                'verbose_name': 'SEO-Einstellungen',
                'verbose_name_plural': 'SEO-Einstellungen',
            },
        ),
    ]
