# Generated by Django 6.0.3 on 2026-03-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_hiromessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visit',
            new_name='generator_v_timesta_bade55_idx',
            old_name='visit_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='generator_v_country_02bfd0_idx',
            old_name='visit_cc_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='generator_v_browser_fa591f_idx',
            old_name='visit_br_idx',
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='privacy_url',
            field=models.URLField(blank=True, help_text='Optionaler Link zur Datenschutzerklärung', verbose_name='Datenschutz-URL'),
        ),
    ]
