# Generated by Django 6.0.3 on 2026-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_rename_visit_ts_idx_generator_v_timesta_bade55_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='donation_url',
            field=models.URLField(blank=True, default='', verbose_name='Spenden-URL (leer = ausblenden)'),
        ),
    ]
