# Generated by Django 6.0.3 on 2026-03-21 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_stacktemplate_description_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name='Registrierung aktiviert')),
                ('email_activation', models.BooleanField(default=False, help_text='Benutzer erhalten Aktivierungslink per E-Mail. Deaktiviert = manuelle Freischaltung durch Admin.', verbose_name='E-Mail-Aktivierung aktivieren')),
                ('email_from', models.EmailField(default='noreply@example.com', help_text='Absender der Aktivierungsmail. SMTP muss in settings.py/Umgebungsvariablen konfiguriert sein.', max_length=254, verbose_name='Absender-E-Mail')),
            ],
            options={
                'verbose_name': 'Registrierungs-Einstellungen',
                'verbose_name_plural': 'Registrierungs-Einstellungen',
            },
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Navbar-Link', 'verbose_name_plural': 'Navbar-Links'},
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='icon',
            field=models.CharField(default='bi-github', help_text='z.B. bi-github, bi-house, bi-globe2', max_length=60, verbose_name='Bootstrap Icon Klasse'),
        ),
        migrations.CreateModel(
            name='UserStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Kurzbeschreibung')),
                ('form_data', models.JSONField()),
                ('is_approved', models.BooleanField(default=False, verbose_name='Freigegeben')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_stacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Stack',
                'verbose_name_plural': 'Community Stacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
