# Generated by Django 6.0.3 on 2026-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_registrationsettings_alter_footerlink_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='z.B. mail.example.com', max_length=200, verbose_name='SMTP-Server')),
                ('port', models.PositiveSmallIntegerField(default=587, verbose_name='Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='STARTTLS verwenden')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL/TLS verwenden (Port 465)')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Benutzername')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Passwort')),
                ('from_email', models.CharField(blank=True, help_text='z.B. "Podman Kube Generator <noreply@example.com>"', max_length=200, verbose_name='Absender')),
                ('admin_email', models.EmailField(blank=True, help_text='Empfänger für Benachrichtigungen (neue Registrierungen). Leer = keine Admin-Mails.', max_length=254, verbose_name='Admin-E-Mail')),
            ],
            options={
                'verbose_name': 'E-Mail-Einstellungen',
                'verbose_name_plural': 'E-Mail-Einstellungen',
            },
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='email_from',
            field=models.EmailField(default='noreply@example.com', help_text='Absender der Aktivierungsmail. SMTP wird unter "E-Mail-Einstellungen" konfiguriert.', max_length=254, verbose_name='Absender-E-Mail'),
        ),
    ]
