# Generated by Django 6.0.3 on 2026-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_emailsettings_alter_registrationsettings_email_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsettings',
            name='password_reset_enabled',
            field=models.BooleanField(default=False, help_text='Zeigt "Passwort vergessen?"-Link auf der Login-Seite. Erfordert funktionierenden SMTP.', verbose_name='Passwort zurücksetzen aktivieren'),
        ),
    ]
