# Generated by Django 6.0.3 on 2026-03-21 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_registrationsettings_password_reset_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=300, verbose_name='Über mich')),
                ('avatar_url', models.URLField(blank=True, help_text='Direktlink zu einem Bild. Leer = Gravatar.', verbose_name='Avatar-URL')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub-Benutzername')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='X / Twitter-Benutzername')),
                ('mastodon', models.CharField(blank=True, help_text='z.B. @user@mastodon.social', max_length=200, verbose_name='Mastodon')),
                ('linkedin', models.CharField(blank=True, max_length=100, verbose_name='LinkedIn-Benutzername')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
    ]
