# Generated by Django 6.0.3 on 2026-03-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstack',
            name='category',
            field=models.CharField(blank=True, default='', help_text='z.B. Datenbank, CMS, Monitoring', max_length=50, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='userstack',
            name='icon',
            field=models.CharField(default='bi-box', help_text='Bootstrap Icons Klasse, z.B. bi-database', max_length=60, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='userstack',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung'),
        ),
    ]
