# Generated by Django 6.0.3 on 2026-03-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_totp_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstack',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Kurzbeschreibung (EN)'),
        ),
    ]
