# Generated by Django 6.0.3 on 2026-03-22 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_userstack_description_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstack',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Aufrufe'),
        ),
        migrations.CreateModel(
            name='StackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, verbose_name='Kommentar')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Sichtbar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='generator.userstack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stack Kommentar',
                'verbose_name_plural': 'Stack Kommentare',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StackLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='generator.userstack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stack Like',
                'verbose_name_plural': 'Stack Likes',
                'unique_together': {('user', 'stack')},
            },
        ),
    ]
