# Generated by Django 6.0.3 on 2026-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_stacklike_stackcomment_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacktemplate',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='userstack',
            name='description_en',
        ),
        migrations.AlterField(
            model_name='stacktemplate',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Short description, e.g. "Self-hosted Git server with web UI"', max_length=160),
        ),
        migrations.AlterField(
            model_name='userstack',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
    ]
