# Generated by Django 6.0.3 on 2026-03-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_remove_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='canvas_enabled',
            field=models.BooleanField(default=True, help_text='Zeigt den visuellen Pod Builder (/canvas/) und den Link auf der Startseite.', verbose_name='Pod Builder aktiviert'),
        ),
    ]
