# Generated by Django 6.0.3 on 2026-03-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_canvas_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AddField(
            model_name='analyticssettings',
            name='track_private_ips',
            field=models.BooleanField(default=False, help_text='Besuche von privaten IP-Adressen (10.x, 172.16.x, 192.168.x) aufzeichnen.', verbose_name='LAN-IPs tracken'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='canvas_enabled',
            field=models.BooleanField(default=True, help_text='Zeigt den visuellen Pod Builder (/builder/) und den Link auf der Startseite.', verbose_name='Pod Builder aktiviert'),
        ),
    ]
