# Generated by Django 6.0.3 on 2026-03-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0026_track_private_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='blocked_ips',
            field=models.TextField(blank=True, default='', help_text='Eine IP pro Zeile. Besuche von diesen IPs werden nicht getrackt.', verbose_name='Gesperrte IPs'),
        ),
        migrations.AddField(
            model_name='analyticssettings',
            name='exclude_paths',
            field=models.TextField(blank=True, default='', help_text='Ein Pfad pro Zeile, z.B. /api/ oder /stack/. Präfix-Matching.', verbose_name='Pfade ausschließen'),
        ),
    ]
