# Generated by Django 6.0.3 on 2026-04-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0030_sitesettings_compose_import_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedyaml',
            name='images',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='generatedyaml',
            name='pod_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
