# Generated by Django 6.0.3 on 2026-04-06 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0031_add_pod_name_images_to_generatedyaml'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticssettings',
            options={'verbose_name': 'Analytics Settings', 'verbose_name_plural': 'Analytics Settings'},
        ),
        migrations.AlterModelOptions(
            name='cookiebannersettings',
            options={'verbose_name': 'Cookie Banner', 'verbose_name_plural': 'Cookie Banner'},
        ),
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name': 'Email Settings', 'verbose_name_plural': 'Email Settings'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Navbar Link', 'verbose_name_plural': 'Navbar Links'},
        ),
        migrations.AlterModelOptions(
            name='hiromessage',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Hiro Message', 'verbose_name_plural': 'Hiro Messages'},
        ),
        migrations.AlterModelOptions(
            name='registrationsettings',
            options={'verbose_name': 'Registration Settings', 'verbose_name_plural': 'Registration Settings'},
        ),
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name': 'SEO Settings', 'verbose_name_plural': 'SEO Settings'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Website Settings', 'verbose_name_plural': 'Website Settings'},
        ),
        migrations.AlterModelOptions(
            name='stackcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Stack Comment', 'verbose_name_plural': 'Stack Comments'},
        ),
        migrations.AlterModelOptions(
            name='totpdevice',
            options={'verbose_name': 'TOTP Device', 'verbose_name_plural': 'TOTP Devices'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='anonymize_ip',
            field=models.BooleanField(default=True, help_text='Store only the first 3 octets, e.g. 192.168.1.x → 192.168.1.0 (GDPR)', verbose_name='Anonymize IP'),
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='blocked_ips',
            field=models.TextField(blank=True, default='', help_text='One IP per line. Visits from these IPs will not be recorded in analytics.', verbose_name='Exclude IPs from analytics'),
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enable tracking'),
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='exclude_paths',
            field=models.TextField(blank=True, default='', help_text='One path per line, e.g. /api/ or /stack/. Prefix matching.', verbose_name='Exclude paths'),
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='Automatically delete visits after X days. 0 = never delete.', verbose_name='Retention (days)'),
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='track_bots',
            field=models.BooleanField(default=False, verbose_name='Track bots'),
        ),
        migrations.AlterField(
            model_name='analyticssettings',
            name='track_private_ips',
            field=models.BooleanField(default=False, help_text='Record visits from private IP addresses (10.x, 172.16.x, 192.168.x).', verbose_name='Track LAN IPs'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='accept_label',
            field=models.CharField(default='Accept all', max_length=80, verbose_name='Button: Accept all'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='accept_label_en',
            field=models.CharField(blank=True, default='Accept all', max_length=80, verbose_name='[EN] Button: Accept all'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='analytics_description',
            field=models.TextField(default='Helps us understand how visitors use the site (anonymised, no cross-site tracking).', verbose_name='Category: Analytics — description'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='analytics_description_en',
            field=models.TextField(blank=True, default='Helps us understand how visitors use the site (anonymised, no cross-site tracking).', verbose_name='[EN] Category: Analytics — description'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='analytics_label',
            field=models.CharField(default='Analytics', max_length=80, verbose_name='Category: Analytics — label'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='analytics_label_en',
            field=models.CharField(blank=True, default='Analytics', max_length=80, verbose_name='[EN] Category: Analytics — label'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='decline_label',
            field=models.CharField(default='Essential only', max_length=80, verbose_name='Button: Decline'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='decline_label_en',
            field=models.CharField(blank=True, default='Essential only', max_length=80, verbose_name='[EN] Button: Decline'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Banner enabled'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='lifetime_days',
            field=models.PositiveSmallIntegerField(default=365, verbose_name='Cookie lifetime (days)'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='position',
            field=models.CharField(choices=[('bottom', 'Bottom (Bar)'), ('top', 'Top (Bar)'), ('modal', 'Center (Modal)')], default='bottom', max_length=10, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='privacy_label',
            field=models.CharField(default='Privacy Policy', max_length=80, verbose_name='Privacy link text'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='privacy_label_en',
            field=models.CharField(blank=True, default='Privacy Policy', max_length=80, verbose_name='[EN] Privacy link text'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='privacy_url',
            field=models.URLField(blank=True, help_text='Optional link to the privacy policy', verbose_name='Privacy URL'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='show_decline_button',
            field=models.BooleanField(default=True, verbose_name='Show decline button'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='text',
            field=models.TextField(default='This website uses cookies for analytics. By clicking "Accept all" you agree to this.', verbose_name='Description text'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='text_en',
            field=models.TextField(blank=True, default='This website uses cookies for analytics. By clicking "Accept all" you agree to this.', verbose_name='[EN] Description text'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='title',
            field=models.CharField(default='Cookies & Privacy', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='title_en',
            field=models.CharField(blank=True, default='Cookies & Privacy', max_length=200, verbose_name='[EN] Title'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Recipient for notifications (new registrations). Empty = no admin emails.', max_length=254, verbose_name='Admin email'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_email',
            field=models.CharField(blank=True, help_text='e.g. "Podman Kube Generator <noreply@example.com>"', max_length=200, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host',
            field=models.CharField(blank=True, help_text='e.g. mail.example.com', max_length=200, verbose_name='SMTP server'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='Use SSL/TLS (port 465)'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Use STARTTLS'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='icon',
            field=models.CharField(default='bi-github', help_text='e.g. bi-github, bi-house, bi-globe2', max_length=60, verbose_name='Bootstrap Icon class'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='label',
            field=models.CharField(max_length=80, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='open_new_tab',
            field=models.BooleanField(default=True, verbose_name='Open in new tab'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='hiromessage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='hiromessage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='hiromessage',
            name='text_de',
            field=models.CharField(max_length=300, verbose_name='Text (German)'),
        ),
        migrations.AlterField(
            model_name='impressumsettings',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='impressumsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='impressumsettings',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name / Company'),
        ),
        migrations.AlterField(
            model_name='impressumsettings',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='impressumsettings',
            name='zusatz',
            field=models.TextField(blank=True, verbose_name='Additional info (liability, copyright etc.)'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='email_activation',
            field=models.BooleanField(default=False, help_text='Users receive an activation link by email. Disabled = manual activation by admin.', verbose_name='Enable email activation'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='email_from',
            field=models.EmailField(default='noreply@example.com', help_text='Sender of activation emails. SMTP is configured under "Email Settings".', max_length=254, verbose_name='Sender email'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='password_reset_enabled',
            field=models.BooleanField(default=False, help_text='Shows "Forgot password?" link on the login page. Requires working SMTP.', verbose_name='Enable password reset'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='registration_enabled',
            field=models.BooleanField(default=True, verbose_name='Registration enabled'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Content of the content attribute in the meta tag', max_length=200, verbose_name='Google Site Verification'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='home_description',
            field=models.TextField(default='Generate Kubernetes YAML for podman play kube for free. Create pod configurations, multi-container stacks and systemd Quadlet instructions in seconds.', max_length=300, verbose_name='Homepage meta description'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='home_title',
            field=models.CharField(default='Podman Kube Generator – Kubernetes YAML for podman play kube', max_length=120, verbose_name='Homepage title tag'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='keywords',
            field=models.CharField(default='podman, kubernetes yaml, podman play kube, container, pod generator, quadlet, systemd, rootless container', max_length=500, verbose_name='Meta keywords'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Absolute URL to preview image, e.g. https://example.com/og.png', verbose_name='OG image URL (Social Media preview)'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='robots_txt',
            field=models.TextField(default='User-agent: *\nAllow: /\nDisallow: /admin/\n\nSitemap: /sitemap.xml', help_text='Served directly as /robots.txt. {site_url} is replaced with the site URL.', verbose_name='robots.txt content'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='site_name',
            field=models.CharField(default='Podman Kube Generator', max_length=100, verbose_name='Site name (og:site_name)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_icon',
            field=models.CharField(default='🦭', max_length=10, verbose_name='Brand icon (Emoji)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Podman Kube Generator', max_length=100, verbose_name='Brand name (Navbar)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name_en',
            field=models.CharField(blank=True, default='Podman Kube Generator', max_length=100, verbose_name='[EN] Brand name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_tagline',
            field=models.CharField(default='podman play kube · systemd quadlet', max_length=200, verbose_name='Brand tagline (Navbar)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_tagline_en',
            field=models.CharField(blank=True, default='podman play kube · systemd quadlet', max_length=200, verbose_name='[EN] Brand tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='canvas_enabled',
            field=models.BooleanField(default=True, help_text='Shows the visual Pod Builder (/builder/) and the link on the home page.', verbose_name='Pod Builder enabled'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='compose_import_timeout',
            field=models.PositiveSmallIntegerField(default=10, help_text='Maximum processing time for a Compose import. 0 = no limit.', verbose_name='Compose Import Timeout (seconds)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='donation_url',
            field=models.URLField(blank=True, default='', verbose_name='Donation URL (empty = hide)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_author',
            field=models.CharField(default='', max_length=100, verbose_name='Footer: Author name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_author_url',
            field=models.URLField(default='', verbose_name='Footer: Author URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_heading',
            field=models.CharField(default='Podman Pod Generator', max_length=200, verbose_name='Homepage H1 heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_heading_en',
            field=models.CharField(blank=True, default='Podman Pod Generator', max_length=200, verbose_name='[EN] Homepage H1 heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_intro',
            field=models.TextField(default='Configure your pod — get ready-to-use Kubernetes YAML for podman play kube.', verbose_name='Homepage intro text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_intro_en',
            field=models.TextField(blank=True, default='Configure your pod — get ready-to-use Kubernetes YAML for podman play kube.', verbose_name='[EN] Homepage intro text'),
        ),
        migrations.AlterField(
            model_name='stackcomment',
            name='body',
            field=models.CharField(max_length=1000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='stackcomment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='stacktemplate',
            name='category',
            field=models.CharField(default='Other', help_text='Category for grouping, e.g. CMS', max_length=50),
        ),
        migrations.AlterField(
            model_name='stacktemplate',
            name='icon',
            field=models.CharField(default='bi-collection', help_text='Bootstrap Icons class, e.g. bi-globe', max_length=60),
        ),
        migrations.AlterField(
            model_name='stacktemplate',
            name='key',
            field=models.SlugField(help_text='Unique key, e.g. wordpress-mariadb', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='stacktemplate',
            name='label',
            field=models.CharField(help_text='Display name, e.g. WordPress + MariaDB', max_length=100),
        ),
        migrations.AlterField(
            model_name='stacktemplate',
            name='stack_data',
            field=models.JSONField(help_text='Stack configuration: pod_name, restart_policy, mode, host_network, containers, init_containers'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, help_text='Local path (set automatically on upload).', max_length=200, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Direct link to an external image. Ignored if an uploaded avatar exists.', verbose_name='Avatar URL (external)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=300, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(blank=True, max_length=100, verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, verbose_name='LinkedIn username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mastodon',
            field=models.CharField(blank=True, help_text='e.g. @user@mastodon.social', max_length=200, verbose_name='Mastodon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, verbose_name='X / Twitter username'),
        ),
        migrations.AlterField(
            model_name='userstack',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g. Database, CMS, Monitoring', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='userstack',
            name='icon',
            field=models.CharField(default='bi-box', help_text='Bootstrap Icons class, e.g. bi-database', max_length=60, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='userstack',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='userstack',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
        migrations.CreateModel(
            name='SavedConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaml_content', models.TextField()),
                ('form_data', models.JSONField()),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='generator.savedconfig')),
            ],
            options={
                'verbose_name': 'Config Version',
                'verbose_name_plural': 'Config Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StackCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stack Collection',
                'verbose_name_plural': 'Stack Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StackCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='generator.stackcollection')),
                ('saved_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='generator.savedconfig')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
                'ordering': ['position', 'added_at'],
                'unique_together': {('collection', 'saved_config')},
            },
        ),
    ]
