# Generated by Django 6.0.3 on 2026-04-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0032_alter_analyticssettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='donation_url',
            field=models.URLField(blank=True, default='', verbose_name='Donation URL (empty = hide)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Footer: Author name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_author_url',
            field=models.URLField(blank=True, default='', verbose_name='Footer: Author URL'),
        ),
    ]
