# Generated by Django 6.0.3 on 2026-04-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0033_clear_personal_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressumsettings',
            name='impressum_enabled',
            field=models.BooleanField(default=False, verbose_name='Show Imprint page'),
        ),
        migrations.AddField(
            model_name='impressumsettings',
            name='privacy_enabled',
            field=models.BooleanField(default=False, verbose_name='Show Privacy Policy page'),
        ),
    ]
