# Generated by Django 6.0.3 on 2026-04-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0034_impressum_privacy_enabled_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiebannersettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Banner enabled'),
        ),
    ]
