# Generated by Django 6.0.3 on 2026-04-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0035_cookie_banner_disabled_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_author',
            field=models.CharField(blank=True, default='Thomas Rzen', max_length=100, verbose_name='Footer: Author name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_author_url',
            field=models.URLField(blank=True, default='https://github.com/Garfieldttt', verbose_name='Footer: Author URL'),
        ),
    ]
