# Generated by Django 6.0.3 on 2026-04-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0036_footer_author_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_author',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_author_url',
        ),
    ]
