# Generated by Django 6.0.3 on 2026-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0037_remove_footer_author_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='robots_txt',
            field=models.TextField(default='User-agent: *\nDisallow: /\n', help_text='Served directly as /robots.txt. {site_url} is replaced with the site URL.', verbose_name='robots.txt content'),
        ),
    ]
