# Generated by Django 6.0.3 on 2026-04-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0038_noindex_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressumsettings',
            name='datenschutz_text',
            field=models.TextField(blank=True, verbose_name='Privacy Policy text'),
        ),
        migrations.AlterField(
            model_name='impressumsettings',
            name='zusatz',
            field=models.TextField(blank=True, verbose_name='Additional info / Imprint (liability, copyright etc.)'),
        ),
    ]
