# Generated by Django 6.0.3 on 2026-04-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0039_add_datenschutz_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stacktemplate',
            name='yaml_content',
            field=models.TextField(blank=True, default='', verbose_name='YAML content (optional)'),
        ),
    ]
