# Generated by Django 6.0.3 on 2026-04-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0040_stacktemplate_yaml_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacktemplate',
            name='yaml_content',
        ),
    ]
