# Generated by Django 6.0.3 on 2026-04-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0041_remove_stacktemplate_yaml_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsettings',
            name='registration_enabled',
            field=models.BooleanField(default=False, verbose_name='Registration enabled'),
        ),
    ]
