# Generated by Django 6.0.3 on 2026-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0042_registration_disabled_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='access_blocked_ips',
            field=models.TextField(blank=True, default='', help_text='One IP per line. These IPs will receive a 403 Forbidden response site-wide.', verbose_name='Block IPs (deny access)'),
        ),
    ]
