# Generated by Django 6.0.3 on 2026-04-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0043_add_access_blocked_ips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enable tracking'),
        ),
    ]
