# Generated by Django 6.0.3 on 2026-04-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0044_analytics_disabled_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstack',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private (not submitted to community)'),
        ),
    ]
